<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Scrutor" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Stan333.SharedKernel\Stan333.SharedKernel.csproj" />
    </ItemGroup>

</Project>
