<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Подключается через ProjectReference; в NuGet публикуется только Shared.Kernel. -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <!-- Граф зависимостей: Framework -> Core -> Kernel. -->
    <ProjectReference Include="..\Shared.Core\Shared.Core.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Exceptions" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

</Project>
