<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\src\Shared.Kernel\Shared.Kernel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions"/>
      <PackageReference Include="TimeZoneConverter"/>
    </ItemGroup>

</Project>
