<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DirectoryService.Contracts\DirectoryService.Contracts.csproj" />
      <ProjectReference Include="..\DirectoryService.Domain\DirectoryService.Domain.csproj" />
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="DirectoryService.UnitTests" />
      <InternalsVisibleTo Include="DirectoryService.IntegrationTests" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console"/>
      <PackageReference Include="Scrutor"/>
      <PackageReference Include="TimeZoneConverter"/>
    </ItemGroup>

</Project>
